title:              GANmapper-Project
email:              jonathan.hecht@hcu-hamburg.de
description:        A Small Research about the Creation of Building Footprints
author:             Jonathan Hecht
baseurl:            "/GANmapper-Project"
url:                "https://jp-hecht.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    jp-hecht
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
